name: Flask CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']  # Testing with different Python versions

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Checkout the code

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt      # Install dependencies from requirements.txt

      - name: Run Tests
        run: |
          pytest tests/  # Run tests from the 'tests' directory (change if needed)

      - name: Upload Test Results (Optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.python-version }}
          path: test-results.xml  # Upload the test results if you want to keep them as artifacts

      - name: Cache Dependencies (Optional)
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip  # Cache pip dependencies for faster future builds
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
