name: Docker Image CI

on:
  workflow_dispatch:  # This allows manual triggering from GitHub UI

jobs:
  build:
    strategy:
      matrix:
        runner: [ubuntu-latest]  

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  

      - name: Define Image Tag
        run: echo "IMAGE_TAG=murali54321/shopping-app:$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_TAG -f Dockerfile .
          docker tag $IMAGE_TAG murali54321/shopping-app:latest
          echo "Built and tagged image: $IMAGE_TAG and latest"
      
      - name: List Docker Images (Debugging)
        run: docker images

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker Image to Docker Hub
        run: |
          docker push $IMAGE_TAG
          docker push murali54321/shopping-app:latest
