name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # Checkout the code

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  
    - name: Build Docker image
      run: docker build -t murali54321/shopping-app -f Dockerfile .
    - name: Pull Docker Image
      run: docker pull murali54321/shopping-app  
    - name: Push Docker Image
      run: docker push murali54321/shopping-app
