name: Docker Image CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  

      - name: Define Image Tag
        id: define_image_tag
        run: echo "IMAGE_TAG=murali54321/shopping-app:$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_TAG -f Dockerfile .
          docker tag $IMAGE_TAG murali54321/shopping-app:latest
          echo "Built and tagged image: $IMAGE_TAG and latest"

      - name: List Docker Images (Debugging)
        run: docker images

      - name: Upload Artifact (Docker Image)
        uses: actions/upload-artifact@v3.1.0  # Updated version for the artifact action
        with:
          name: docker-image
          path: .

      - name: Set IMAGE_TAG as an output
        id: set_outputs
        run: echo "image_tag=$IMAGE_TAG" >> $GITHUB_ENV

  test:
    name: Test Docker Image
    runs-on: ubuntu-latest
    needs: build  # Run only after build is complete

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Built Image
        uses: actions/download-artifact@v3.1.0  # Updated version for the artifact action
        with:
          name: docker-image
          path: .

      - name: Run Container for Testing
        run: |
          docker run -d --name test-container ${{ needs.build.outputs.image_tag }}
          sleep 5  # Give container time to start
          docker ps | grep test-container  # Verify it is running

      - name: Run Tests Inside the Container
        run: |
          docker exec test-container curl -f http://localhost:5000 || exit 1

      - name: Cleanup Test Container
        run: docker rm -f test-container
  
  deploy:
    name: Deploy Docker Image
    runs-on: ubuntu-latest
    needs: test  # Run only after tests pass

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ needs.build.outputs.image_tag }}
          docker push murali54321/shopping-app:latest
