name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # Checkout the code

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Correct action for setting up Docker Buildx
