name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # Checkout the code

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Correct action for setting up Docker Buildx

    - name: Log in to Docker Hub
      uses: docker/login-action@v2  # Correct action for logging in to Docker Hub
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag murali54321/shopping-app:$(date +%s)  # Build and tag the image
        docker push murali54321/shopping-app:$(date +%s)  # Push the image to Docker Hub

    - name: Pull the Docker image
      run: docker pull murali54321/shopping-app:$(date +%s)  # Pull the image with the same tag
